### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by jansule** [bramstein/css-font-parser#12]
Thanks for merging https://github.com/bramstein/css-font-parser/pull/11 @bramstein!

Could you publish a new version that includes the added the spdx identifier to the package lock, so we can take advantage of it?

Thanks a lot!

**Comment by bramstein** [comment]
Thanks for the reminder (totally slipped my mind). Published as v2.0.1.

**Comment by jansule** [comment]
Great! Thanks for addressing this so fast
