### ISSUE TITLE
0.2.2 version can't find ` lib/parser.js` file

### ISSUE THREAD

**Issue by luckyufei** [bramstein/css-font-parser#3]
hello,  `css-font-parser`@0.2.2 version can't work in my project.  bescause in its package.json ` main value is `lib/parser.js`, but the project don't have this file.  please fix it. 

`font-spider` package require your `css-font-parser`.

**Comment by bramstein** [comment]
Whoops. Sorry about that, I missed that when I merged in another pull request. Should be fixed now in 0.2.3.
