### ISSUE TITLE
Failed to parse font-family containing escape characters

### ISSUE THREAD

**Issue by izogfif** [bramstein/css-font-parser#6]
> window.cssFontParser("1rem Courier\000020New")

Gives `{"font-family":["Courier\\000020New"],"font-size":"1rem"}` instead of `{"font-family":["Courier New"],"font-size":"1rem"}`

**Comment by papandreou** [comment]
Also fails to parse escaped spaces, eg. `12px Font Awesome\ 5 Free` (comes out as `null`).

**Comment by bramstein** [comment]
This is fixed in v1.0.1.
